### ISSUE TITLE
Make a new release to ensure nfov is not removed from Homebrew

### ISSUE THREAD

**Issue by 0risc** [nrlquaker/nfov#250]
Homebrew has decided to deprecate nfov because of the lack of recent releases: https://github.com/Homebrew/homebrew-cask/pull/184697.

Even if you don't have a new release ready with bug fixes or features, you may want to bump some dependencies and make a new release to prevent nfov from being removed from Homebrew.

**Comment by nrlquaker** [comment]
nfov is not supported anymore. I'm not posting a new release to trick homebrew to think its in development.
